#!/usr/bin/env node
// scripts/build-lures.mjs — Generates src/lures-data.js from ../lures/**/*.md
// Bundles the entire lure collection into the Worker: zero state = zero failure.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const luresDir = path.resolve(root, "..", "lures");
const outFile = path.resolve(root, "src", "lures-data.js");

function walk(dir) {
  const out = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  );
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.endsWith(".md")) out.push(full);
  }
  return out;
}

const files = walk(luresDir);
const entries = [];
for (const full of files) {
  const rel = path
    .relative(luresDir, full)
    .replace(/\\/g, "/")
    .replace(/\.md$/, "");
  const content = fs.readFileSync(full, "utf-8");
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");
  entries.push({ rel, escaped });
}

const output = `// Auto-generated by scripts/build-lures.mjs — Do not edit directly
// Source of truth: lures/ at repo root. Regenerated on every build/deploy.
export const LURE_FILES = {
${entries.map((e) => `  "${e.rel}": \`${e.escaped}\`,`).join("\n")}
};
`;

fs.writeFileSync(outFile, output);
console.log(
  `✓ Generated ${outFile} with ${entries.length} lures (${(Buffer.byteLength(output, "utf-8") / 1024).toFixed(1)} KB)`
);
